### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'libgtk-win32-2.0-0.dll

### ISSUE THREAD

**Issue by Shadowblitz16** [mono/xwt#937]
I am having more problems with this library.

```
System.Exception
  HResult=0x80131500
  Message=Toolkit could not be loaded
  Source=Xwt
  StackTrace:
   at Xwt.Toolkit.LoadBackend(String type, Boolean isGuest, Boolean throwIfFails)
   at Xwt.Toolkit.Load(String fullTypeName, Boolean isGuest)
   at Xwt.Application.Initialize(String backendType)
   at Xwt.Application.Initialize(ToolkitType type)
   at XwtTest.Program.Main(String[] args) in C:\Users\Shadowblitz16\source\repos\XwtTest\XwtTest\Program.cs:line 12

Inner Exception 1:
DllNotFoundException: Unable to load DLL 'libgtk-win32-2.0-0.dll': The specified procedure could not be found. (Exception from HRESULT: 0x8007007F)
```

```
using System;
using Xwt;

namespace XwtTest
{
    class Program
    {

        [STAThread]
        static void Main(string[] args)
        {
            Application.Initialize(ToolkitType.Gtk);

            //Create the Window
            var mainWindow = new Window()
            {
                Title = "HelloWorld",
                Width = 640,
                Height = 480
            };

            mainWindow.Show();
            Application.Run();
            mainWindow.Dispose();
        }
    }
}
```

notes...
-Xwt and Xwt.Gtk are References in the project
-Mono 32bit and Gtk# is installed

**Comment by Shadowblitz16** [comment]
@sevoku can I get some info on this I still can't get this to work.

**Comment by Codes-Breaker** [comment]
> @sevoku can I get some info on this I still can't get this to work.

same, have you ever solved this?
